name: Main Branch Pull Request
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Navigate to frontend dir
        run: cd frontend
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
