name: Main Branch Pull Request
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Create fake certificates
        run: mkdir certificates && echo 'fake' >> ./certificates/ssl_certificate.pem && echo 'fake' >> ./certificates/ssl_certificate_key.pem
      - name: Build docker image
        run: docker build -t app .
